### ISSUE TITLE
Problem with `bosh deploy`

### ISSUE THREAD

**Issue by michaellihs** [mariash/learn-bosh#18]
When I follow the tutorial on my Mac, I get stuck at the step 4 that says "And deploy". Running

```
bosh deploy
```

it takes a while, then I get an error message

```
Deploying
---------
Are you sure you want to deploy? (type 'yes' to continue): yes

Director task 3
  Started preparing deployment > Preparing deployment. Done (00:00:00)

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

  Started compiling packages
  Started compiling packages > ruby/25ebd4176ea1a42b0e03eeac5c0f13bd49b97a33. Done (00:01:53)
  Started compiling packages > simple_server/67e4bce4fa86bababb4f832871d09dc34a640de3. Done (00:00:10)
     Done compiling packages (00:02:03)

  Started creating missing vms > app/0 (9adca58a-0412-450a-9271-2e28f7e28853). Done (00:00:07)

  Started updating job app > app/0 (9adca58a-0412-450a-9271-2e28f7e28853) (canary). Failed: `app/0 (9adca58a-0412-450a-9271-2e28f7e28853)' is not running after update. Review logs for failed jobs: app (00:01:12)

Error 400007: `app/0 (9adca58a-0412-450a-9271-2e28f7e28853)' is not running after update. Review logs for failed jobs: app

Task 3 error
```

When I now run `bosh task 6 --debug` I get a lengthy error message, which holds the following part as the relevant information:

```
D, [2016-03-18 15:40:36 #23467] [] DEBUG -- DirectorJobRunner: RECEIVED: director.140e8296-0fac-4bab-b4b6-a47e9f2441ef.a6f92b9a-f8cc-4ae9-adc2-33259b8f1e31 {"value":{"properties":{"logging":{"max_log_file_size":""}},"job":{"name":"app","release":"","template":"app","version":"6bc524d4b74f4314f4c17f10b802694e1a830efe","sha1":"058eacfd61a157d62d5da061986b705e7bd9866a","blobstore_id":"13b91f8b-ca58-4d65-b7bb-9593f6739de9","templates":[{"name":"app","version":"6bc524d4b74f4314f4c17f10b802694e1a830efe","sha1":"058eacfd61a157d62d5da061986b705e7bd9866a","blobstore_id":"13b91f8b-ca58-4d65-b7bb-9593f6739de9"}]},"packages":{"ruby":{"name":"ruby","version":"25ebd4176ea1a42b0e03eeac5c0f13bd49b97a33.1","sha1":"ccafadef678165fa7909db2870d89e28f11c7fd1","blobstore_id":"96f0e059-f329-444b-6eab-05c2bd357ad4"},"simple_server":{"name":"simple_server","version":"67e4bce4fa86bababb4f832871d09dc34a640de3.1","sha1":"fc29d5c0a6456fccf5bb49ece4435892f45f3cb4","blobstore_id":"e3b89335-935d-48aa-72f2-418a5145fcd9"}},"configuration_hash":"f4b5c3c7fdeaf3fdd6f393ab83104e18f9748ff5","networks":{"default":{"cloud_properties":{"name":"random"},"default":["dns","gateway"],"ip":"10.244.0.2","netmask":"255.255.255.240"}},"resource_pool":{},"deployment":"learn-bosh","index":0,"id":"6cfec0b2-a4c6-45ca-9297-95d2bcfa00d9","persistent_disk":0,"rendered_templates_archive":{"sha1":"1078cf6559a42c118e78629a9514c77beafc2292","blobstore_id":"147f2e6d-9ae5-4efd-8ebe-7a912e4e3cc7"},"agent_id":"ba86fc92-7ae4-43aa-8c70-5dffee7b4507","bosh_protocol":"1","job_state":"failing","processes":[{"name":"app","state":"failing","uptime":{},"mem":{"percent":0},"cpu":{"total":0}}],"vm":{"name":"85b2a46e-a2d7-48bd-5760-dae4b9267a82"},"ntp":{"message":"file missing"}}}
E, [2016-03-18 15:40:36 #23467] [canary_update(app/0 (6cfec0b2-a4c6-45ca-9297-95d2bcfa00d9))] ERROR -- DirectorJobRunner: Error updating canary instance: #<Bosh::Director::AgentJobNotRunning: `app/0 (6cfec0b2-a4c6-45ca-9297-95d2bcfa00d9)' is not running after update. Review logs for failed jobs: app>
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/instance_updater/state_applier.rb:48:in `post_start'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/instance_updater/state_applier.rb:30:in `apply'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/instance_updater.rb:101:in `block in update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/instance_updater/instance_state.rb:5:in `with_instance_update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/instance_updater.rb:46:in `update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/job_updater.rb:111:in `block (2 levels) in update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/job_updater.rb:109:in `block in update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/event_log.rb:97:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/event_log.rb:97:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/job_updater.rb:108:in `update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/job_updater.rb:103:in `block (2 levels) in update_canaries'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.0/lib/common/thread_pool.rb:77:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
E, [2016-03-18 15:40:36 #23467] [] ERROR -- DirectorJobRunner: Worker thread raised exception: `app/0 (6cfec0b2-a4c6-45ca-9297-95d2bcfa00d9)' is not running after update. Review logs for failed jobs: app - /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/instance_updater/state_applier.rb:48:in `post_start'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/instance_updater/state_applier.rb:30:in `apply'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/instance_updater.rb:101:in `block in update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/instance_updater/instance_state.rb:5:in `with_instance_update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/instance_updater.rb:46:in `update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/job_updater.rb:111:in `block (2 levels) in update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/job_updater.rb:109:in `block in update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/event_log.rb:97:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/event_log.rb:97:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/job_updater.rb:108:in `update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/job_updater.rb:103:in `block (2 levels) in update_canaries'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.0/lib/common/thread_pool.rb:77:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2016-03-18 15:40:36 #23467] [] DEBUG -- DirectorJobRunner: Thread is no longer needed, cleaning up
D, [2016-03-18 15:40:36 #23467] [task:6] DEBUG -- DirectorJobRunner: Shutting down pool
D, [2016-03-18 15:40:36 #23467] [task:6] DEBUG -- DirectorJobRunner: (0.000348s) SELECT NULL
D, [2016-03-18 15:40:36 #23467] [task:6] DEBUG -- DirectorJobRunner: (0.000353s) SELECT "stemcells".* FROM "stemcells" INNER JOIN "deployments_stemcells" ON (("deployments_stemcells"."stemcell_id" = "stemcells"."id") AND ("deployments_stemcells"."deployment_id" = 1))
D, [2016-03-18 15:40:36 #23467] [task:6] DEBUG -- DirectorJobRunner: Deleting lock: lock:deployment:learn-bosh
D, [2016-03-18 15:40:36 #23467] [] DEBUG -- DirectorJobRunner: Lock renewal thread exiting
D, [2016-03-18 15:40:36 #23467] [task:6] DEBUG -- DirectorJobRunner: Deleted lock: lock:deployment:learn-bosh
I, [2016-03-18 15:40:36 #23467] [task:6]  INFO -- DirectorJobRunner: sending update deployment error event
D, [2016-03-18 15:40:36 #23467] [task:6] DEBUG -- DirectorJobRunner: SENT: hm.director.alert {"id":"e5544121-f833-4741-a4d5-46d32dfb4cba","severity":3,"source":"director","title":"director - error during update deployment","summary":"Error during update deployment for 'learn-bosh' against Director '17a45148-1d00-43bc-af28-9882e5a6535a': #<Bosh::Director::AgentJobNotRunning: `app/0 (6cfec0b2-a4c6-45ca-9297-95d2bcfa00d9)' is not running after update. Review logs for failed jobs: app>","created_at":1458315636}
E, [2016-03-18 15:40:36 #23467] [task:6] ERROR -- DirectorJobRunner: `app/0 (6cfec0b2-a4c6-45ca-9297-95d2bcfa00d9)' is not running after update. Review logs for failed jobs: app
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/instance_updater/state_applier.rb:48:in `post_start'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/instance_updater/state_applier.rb:30:in `apply'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/instance_updater.rb:101:in `block in update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/instance_updater/instance_state.rb:5:in `with_instance_update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/instance_updater.rb:46:in `update'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/job_updater.rb:111:in `block (2 levels) in update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/job_updater.rb:109:in `block in update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/event_log.rb:97:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/event_log.rb:97:in `advance_and_track'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/job_updater.rb:108:in `update_canary_instance'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3215.0/lib/bosh/director/job_updater.rb:103:in `block (2 levels) in update_canaries'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.0/lib/common/thread_pool.rb:77:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.0/lib/common/thread_pool.rb:63:in `loop'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3215.0/lib/common/thread_pool.rb:63:in `block in create_thread'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
D, [2016-03-18 15:40:36 #23467] [task:6] DEBUG -- DirectorJobRunner: (0.000231s) SELECT NULL
D, [2016-03-18 15:40:36 #23467] [task:6] DEBUG -- DirectorJobRunner: (0.000102s) BEGIN
D, [2016-03-18 15:40:36 #23467] [task:6] DEBUG -- DirectorJobRunner: (0.000146s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2016-03-18 15:40:36.452225+0000', "description" = 'create deployment', "result" = '`app/0 (6cfec0b2-a4c6-45ca-9297-95d2bcfa00d9)'' is not running after update. Review logs for failed jobs: app', "output" = '/var/vcap/store/director/tasks/6', "checkpoint_time" = '2016-03-18 15:39:15.228338+0000', "type" = 'update_deployment', "username" = 'admin', "deployment_name" = 'learn-bosh' WHERE ("id" = 6)
D, [2016-03-18 15:40:36 #23467] [task:6] DEBUG -- DirectorJobRunner: (0.000577s) COMMIT
I, [2016-03-18 15:40:36 #23467] []  INFO -- DirectorJobRunner: Task took 1 minute 21.228146143999993 seconds to process.

Task 6 error
```

Can you maybe tell me how I can debug the problem? I can ssh into the Vagrant Box that runs BOSH Lite but I don't know what to do from there on...

Thanks a lot for any suggestions on how to get the tutorial up and running.

**Comment by dpb587-pivotal** [comment]
Discussion happened in slack#bosh - this can be closed.

**Comment by mariash** [comment]
Thanks @dpb587-pivotal!
